spring.application.name=questionnaire
# Server
server.port=8080

# H2 In-Memory Database (for development)
spring.datasource.url=jdbc:h2:mem:questionnairedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA ? auto-creates tables from your entities
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true


# See security decisions in the console (helpful when debugging)
logging.level.org.springframework.security=DEBUG